octopus:
  environments:
    - development
    -production

  development:
    shard_one:
        # adapter: oracle_enhanced
        # username: CPI
        # password: cpi12345!
        # host: 172.16.110.8
        # port: 1521
        # database: DEMO

    shard_two:
      adapter: mysql2
      host: localhost
      port: 3306
      adapter: mysql2
      username: root
      password: Fortune
      database: fgen

production:

    shard_two:
      adapter: mysql2
      host: localhost
      port: 3306
      adapter: mysql2
      username: root
      password: Fortune
      database: fgen
